//
//  Constants.swift
//  Glance
//
//  Created by Nazarii Zomko on 27.03.2023.
//

import Foundation


struct Constants {
    
    // latest update of default rates: 2023-03-27
    static let currencies = [
        Currency(code: "1inch", name: "1inch Network", symbol: "", rate: 1.996957),
        Currency(code: "axs", name: "AXS", symbol: "", rate: 0.120928),
        Currency(code: "afn", name: "Afghan Afghani", symbol: "", rate: 86.751081),
        Currency(code: "all", name: "Albanian Lek", symbol: "", rate: 106.52926),
        Currency(code: "dzd", name: "Algerian Dinar", symbol: "", rate: 135.833106),
        Currency(code: "algo", name: "Algorand", symbol: "", rate: 4.839828),
        Currency(code: "aoa", name: "Angolan Kwanza", symbol: "", rate: 504.801202),
        Currency(code: "ars", name: "Argentine Peso", symbol: "", rate: 205.259978),
        Currency(code: "amd", name: "Armenian Dram", symbol: "", rate: 388.070527),
        Currency(code: "awg", name: "Aruban Florin", symbol: "", rate: 1.8),
        Currency(code: "ar", name: "Arweave", symbol: "", rate: 0.124874),
        Currency(code: "atom", name: "Atomic Coin", symbol: "", rate: 0.089297),
        Currency(code: "aud", name: "Australian Dollar", symbol: "", rate: 1.503351),
        Currency(code: "avax", name: "Avalanche", symbol: "", rate: 0.058745),
        Currency(code: "azn", name: "Azerbaijani Manat", symbol: "", rate: 1.70397),
        Currency(code: "bsd", name: "Bahamian Dollar", symbol: "", rate: 1.000895),
        Currency(code: "bhd", name: "Bahraini Dinar", symbol: "", rate: 0.376351),
        Currency(code: "bbd", name: "Bajan Dollar", symbol: "", rate: 2.020991),
        Currency(code: "bake", name: "Bakerytoken", symbol: "", rate: 5.540676),
        Currency(code: "bdt", name: "Bangladeshi Taka", symbol: "", rate: 105.197454),
        Currency(code: "bat", name: "Basic Attention Token", symbol: "", rate: 4.238448),
        Currency(code: "sand", name: "Beachcoin", symbol: "", rate: 1.597827),
        Currency(code: "byr", name: "Belarusian Ruble", symbol: "", rate: 19600.006248),
        Currency(code: "bzd", name: "Belize Dollar", symbol: "", rate: 2.017486),
        Currency(code: "bmd", name: "Bermudan Dollar", symbol: "", rate: 1.0),
        Currency(code: "btn", name: "Bhutan Currency", symbol: "", rate: 82.523793),
        Currency(code: "bnb", name: "Binance Coin", symbol: "", rate: 0.003093),
        Currency(code: "busd", name: "Binance USD", symbol: "", rate: 1.000308),
        Currency(code: "bsw", name: "Biswap", symbol: "", rate: 5.534113),
        Currency(code: "btc", name: "Bitcoin", symbol: "", rate: 3.6e-05),
        Currency(code: "btcb", name: "Bitcoin BEP2", symbol: "", rate: 3.6e-05),
        Currency(code: "bch", name: "Bitcoin Cash", symbol: "", rate: 0.007965),
        Currency(code: "btg", name: "Bitcoin Gold", symbol: "", rate: 0.064024),
        Currency(code: "bsv", name: "Bitcoin SV", symbol: "", rate: 0.027425),
        Currency(code: "bob", name: "Bolivian Boliviano", symbol: "", rate: 6.915548),
        Currency(code: "bam", name: "Bosnia-herzegovina Convertible Mark", symbol: "", rate: 1.823013),
        Currency(code: "bwp", name: "Botswanan Pula", symbol: "", rate: 13.204342),
        Currency(code: "brl", name: "Brazilian Real", symbol: "", rate: 5.246606),
        Currency(code: "bnd", name: "Brunei Dollar", symbol: "", rate: 1.335017),
        Currency(code: "bgn", name: "Bulgarian Lev", symbol: "", rate: 1.818005),
        Currency(code: "bif", name: "Burundian Franc", symbol: "", rate: 2081.799949),
        Currency(code: "xpf", name: "CFP Franc", symbol: "", rate: 112.250399),
        Currency(code: "khr", name: "Cambodian Riel", symbol: "", rate: 4063.734804),
        Currency(code: "cad", name: "Canadian Dollar", symbol: "", rate: 1.380351),
        Currency(code: "cve", name: "Cape Verdean Escudo", symbol: "", rate: 102.770625),
        Currency(code: "ada", name: "Cardano", symbol: "", rate: 2.841777),
        Currency(code: "kyd", name: "Cayman Islands Dollar", symbol: "", rate: 0.834091),
        Currency(code: "celo", name: "Celo", symbol: "", rate: 1.675478),
        Currency(code: "xaf", name: "Central African CFA Franc", symbol: "", rate: 611.424319),
        Currency(code: "link", name: "Chainlink", symbol: "", rate: 0.140514),
        Currency(code: "xch", name: "Chia", symbol: "", rate: 0.026491),
        Currency(code: "clp", name: "Chilean Peso", symbol: "", rate: 810.50417),
        Currency(code: "chz", name: "Chiliz", symbol: "", rate: 8.396472),
        Currency(code: "cny", name: "Chinese Yuan", symbol: "", rate: 6.868043),
        Currency(code: "cop", name: "Colombian Peso", symbol: "", rate: 4750.231514),
        Currency(code: "kmf", name: "Comorian Franc", symbol: "", rate: 461.740532),
        Currency(code: "comp", name: "Compound Coin", symbol: "", rate: 0.023762),
        Currency(code: "cdf", name: "Congolese Franc", symbol: "", rate: 2052.001016),
        Currency(code: "cvx", name: "Convex Finance", symbol: "", rate: 0.195474),
        Currency(code: "crc", name: "Costa Rican Colón", symbol: "", rate: 540.213238),
        Currency(code: "crv", name: "Cravy", symbol: "", rate: 1.088415),
        Currency(code: "hrk", name: "Croatian Kuna", symbol: "", rate: 7.018276),
        Currency(code: "cro", name: "Crypto.com Chain Token", symbol: "", rate: 14.468132),
        Currency(code: "cup", name: "Cuban Peso", symbol: "", rate: 26.500008),
        Currency(code: "czk", name: "Czech Koruna", symbol: "", rate: 22.002911),
        Currency(code: "dai", name: "Dai", symbol: "", rate: 1.000993),
        Currency(code: "dkk", name: "Danish Krone", symbol: "", rate: 6.925406),
        Currency(code: "dash", name: "Dash", symbol: "", rate: 0.017181),
        Currency(code: "mana", name: "Decentraland", symbol: "", rate: 1.713227),
        Currency(code: "dcr", name: "Decred", symbol: "", rate: 0.046869),
        Currency(code: "djf", name: "Djiboutian Franc", symbol: "", rate: 177.72045),
        Currency(code: "doge", name: "Dogecoin", symbol: "", rate: 13.511321),
        Currency(code: "dop", name: "Dominican Peso", symbol: "", rate: 54.916087),
        Currency(code: "eos", name: "EOS", symbol: "", rate: 0.893286),
        Currency(code: "egp", name: "Egyptian Pound", symbol: "", rate: 30.838869),
        Currency(code: "ern", name: "Eritrean Nakfa", symbol: "", rate: 15.000005),
        Currency(code: "eth", name: "Ether", symbol: "", rate: 0.000571),
        Currency(code: "etc", name: "Ethereum Classic", symbol: "", rate: 0.049467),
        Currency(code: "etb", name: "Ethiopian Birr", symbol: "", rate: 53.910795),
        Currency(code: "eur", name: "Euro", symbol: "€", rate: 0.927504),
        Currency(code: "fkp", name: "Falkland Islands Pound", symbol: "", rate: 0.818079),
        Currency(code: "fjd", name: "Fijian Dollar", symbol: "", rate: 2.218305),
        Currency(code: "flow", name: "Flow", symbol: "", rate: 1.045829),
        Currency(code: "gmd", name: "Gambian Dalasi", symbol: "", rate: 61.503873),
        Currency(code: "gel", name: "Georgian Lari", symbol: "", rate: 2.575041),
        Currency(code: "ghs", name: "Ghanaian Cedi", symbol: "", rate: 12.259719),
        Currency(code: "gip", name: "Gibraltar Pound", symbol: "", rate: 0.818079),
        Currency(code: "gtq", name: "Guatemalan Quetzal", symbol: "", rate: 7.809605),
        Currency(code: "gnf", name: "Guinean Franc", symbol: "", rate: 8611.724903),
        Currency(code: "gyd", name: "Guyanaese Dollar", symbol: "", rate: 211.17585),
        Currency(code: "htg", name: "Haitian Gourde", symbol: "", rate: 155.400669),
        Currency(code: "hnt", name: "Helium", symbol: "", rate: 0.694844),
        Currency(code: "hnl", name: "Honduran Lempira", symbol: "", rate: 24.685889),
        Currency(code: "hkd", name: "Hong Kong Dollar", symbol: "", rate: 7.849953),
        Currency(code: "huf", name: "Hungarian Forint", symbol: "", rate: 357.440502),
        Currency(code: "miota", name: "IOTA", symbol: "", rate: 4.886038),
        Currency(code: "isk", name: "Icelandic Króna", symbol: "", rate: 139.50386),
        Currency(code: "inr", name: "Indian Rupee", symbol: "", rate: 82.347477),
        Currency(code: "idr", name: "Indonesian Rupiah", symbol: "", rate: 15166.054834),
        Currency(code: "irr", name: "Iranian Rial", symbol: "", rate: 42250.013821),
        Currency(code: "iqd", name: "Iraqi Dinar", symbol: "", rate: 1457.845465),
        Currency(code: "ils", name: "Israeli New Shekel", symbol: "", rate: 3.594612),
        Currency(code: "jmd", name: "Jamaican Dollar", symbol: "", rate: 151.101715),
        Currency(code: "jpy", name: "Japanese Yen", symbol: "¥", rate: 130.750427),
        Currency(code: "jep", name: "Jersey Pound", symbol: "", rate: 0.818079),
        Currency(code: "jod", name: "Jordanian Dinar", symbol: "", rate: 0.709405),
        Currency(code: "kava", name: "Kava", symbol: "", rate: 1.180126),
        Currency(code: "kzt", name: "Kazakhstani Tenge", symbol: "", rate: 457.971512),
        Currency(code: "kes", name: "Kenyan Shilling", symbol: "", rate: 131.403846),
        Currency(code: "kcs", name: "Kucoin", symbol: "", rate: 0.114909),
        Currency(code: "kwd", name: "Kuwaiti Dinar", symbol: "", rate: 0.30617),
        Currency(code: "kgs", name: "Kyrgystani Som", symbol: "", rate: 87.420413),
        Currency(code: "lak", name: "Laotian Kip", symbol: "", rate: 16908.607415),
        Currency(code: "lvl", name: "Latvian Lats", symbol: "", rate: 0.604891),
        Currency(code: "lbp", name: "Lebanese Pound", symbol: "", rate: 15022.303229),
        Currency(code: "lsl", name: "Lesotho Loti", symbol: "", rate: 18.420388),
        Currency(code: "lrd", name: "Liberian Dollar", symbol: "", rate: 161.050433),
        Currency(code: "lyd", name: "Libyan Dinar", symbol: "", rate: 4.763061),
        Currency(code: "ltc", name: "Litecoin", symbol: "", rate: 0.010878),
        Currency(code: "ltl", name: "Lithuanian Litas", symbol: "", rate: 2.952742),
        Currency(code: "mop", name: "Macanese Pataca", symbol: "", rate: 8.092403),
        Currency(code: "mkd", name: "Macedonian Denar", symbol: "", rate: 57.436356),
        Currency(code: "mga", name: "Malagasy Ariary", symbol: "", rate: 4316.15924),
        Currency(code: "mwk", name: "Malawian Kwacha", symbol: "", rate: 1027.918814),
        Currency(code: "myr", name: "Malaysian Ringgit", symbol: "", rate: 4.42804),
        Currency(code: "mvr", name: "Maldivian Rufiyaa", symbol: "", rate: 15.403746),
        Currency(code: "mro", name: "Mauritanian Ouguiya", symbol: "", rate: 356.999942),
        Currency(code: "mur", name: "Mauritian Rupee", symbol: "", rate: 46.010394),
        Currency(code: "mxn", name: "Mexican Peso", symbol: "", rate: 18.44151),
        Currency(code: "mdl", name: "Moldovan Leu", symbol: "", rate: 18.530313),
        Currency(code: "xmr", name: "Monero", symbol: "", rate: 0.006152),
        Currency(code: "mnt", name: "Mongolian Tugrik", symbol: "", rate: 3528.952345),
        Currency(code: "mad", name: "Moroccan Dirham", symbol: "", rate: 10.253424),
        Currency(code: "mzn", name: "Mozambican Metical", symbol: "", rate: 63.103752),
        Currency(code: "mmk", name: "Myanmar Kyat", symbol: "", rate: 2101.741713),
        Currency(code: "neo", name: "NEO", symbol: "", rate: 0.083627),
        Currency(code: "nad", name: "Namibian Dollar", symbol: "", rate: 18.420383),
        Currency(code: "npr", name: "Nepalese Rupee", symbol: "", rate: 132.037846),
        Currency(code: "byn", name: "New Belarusian Ruble", symbol: "", rate: 2.526332),
        Currency(code: "twd", name: "New Taiwan Dollar", symbol: "", rate: 30.334913),
        Currency(code: "nzd", name: "New Zealand Dollar", symbol: "", rate: 1.611605),
        Currency(code: "nio", name: "Nicaraguan Córdoba", symbol: "", rate: 36.613114),
        Currency(code: "ngn", name: "Nigerian Naira", symbol: "", rate: 460.480523),
        Currency(code: "kpw", name: "North Korean Won", symbol: "", rate: 899.971506),
        Currency(code: "nok", name: "Norwegian Krone", symbol: "", rate: 10.467988),
        Currency(code: "omr", name: "Omani Rial", symbol: "", rate: 0.384206),
        Currency(code: "pkr", name: "Pakistani Rupee", symbol: "", rate: 283.116381),
        Currency(code: "pab", name: "Panamanian Balboa", symbol: "", rate: 1.000867),
        Currency(code: "pgk", name: "Papua New Guinean Kina", symbol: "", rate: 3.526825),
        Currency(code: "pyg", name: "Paraguayan Guarani", symbol: "", rate: 7189.727528),
        Currency(code: "php", name: "Philippine Peso", symbol: "", rate: 54.288056),
        Currency(code: "pln", name: "Polish Złoty", symbol: "zł", rate: 4.357618),
        Currency(code: "matic", name: "Polygon", symbol: "", rate: 0.922621),
        Currency(code: "gbp", name: "British Pound", symbol: "£", rate: 0.817862),
        Currency(code: "qar", name: "Qatari Rial", symbol: "", rate: 3.64104),
        Currency(code: "qnt", name: "Quant", symbol: "", rate: 0.008181),
        Currency(code: "ron", name: "Romanian Leu", symbol: "", rate: 4.58104),
        Currency(code: "rub", name: "Russian Ruble", symbol: "", rate: 77.280398),
        Currency(code: "rwf", name: "Rwandan Franc", symbol: "", rate: 1099.05713),
        Currency(code: "shp", name: "Saint Helena Pound", symbol: "", rate: 1.21675),
        Currency(code: "svc", name: "Salvadoran Colón", symbol: "", rate: 8.757779),
        Currency(code: "wst", name: "Samoan Tala", symbol: "", rate: 2.745636),
        Currency(code: "sar", name: "Saudi Riyal", symbol: "", rate: 3.75643),
        Currency(code: "rsd", name: "Serbian Dinar", symbol: "", rate: 108.818026),
        Currency(code: "scr", name: "Seychellois Rupee", symbol: "", rate: 13.050781),
        Currency(code: "shib", name: "Shiba Inu", symbol: "", rate: 94947.563265),
        Currency(code: "sle", name: "Sierra Leonean Leone", symbol: "", rate: 21.044279),
        Currency(code: "xag", name: "Silver Ounce", symbol: "AG", rate: 0.043049),
        Currency(code: "sgd", name: "Singapore Dollar", symbol: "", rate: 1.332905),
        Currency(code: "pen", name: "Sol", symbol: "", rate: 3.773757),
        Currency(code: "sbd", name: "Solomon Islands Dollar", symbol: "", rate: 8.200168),
        Currency(code: "sos", name: "Somali Shilling", symbol: "", rate: 569.503846),
        Currency(code: "zar", name: "South African Rand", symbol: "", rate: 18.170309),
        Currency(code: "krw", name: "South Korean Won", symbol: "", rate: 1295.830796),
        Currency(code: "vef", name: "Sovereign Bolivar", symbol: "", rate: 2425265.1384),
        Currency(code: "lkr", name: "Sri Lankan Rupee", symbol: "", rate: 323.319517),
        Currency(code: "xlm", name: "Stellar", symbol: "", rate: 10.950202),
        Currency(code: "sdg", name: "Sudanese Pound", symbol: "", rate: 593.503868),
        Currency(code: "srd", name: "Surinamese Dollar", symbol: "", rate: 35.45405),
        Currency(code: "szl", name: "Swazi Lilangeni", symbol: "", rate: 18.256223),
        Currency(code: "sek", name: "Swedish Krona", symbol: "", rate: 10.656719),
        Currency(code: "chf", name: "Swiss Franc", symbol: "", rate: 0.920095),
        Currency(code: "syp", name: "Syrian Pound", symbol: "", rate: 2512.492151),
        Currency(code: "std", name: "São Tomé And Príncipe Dobra (pre-2018)", symbol: "", rate: 20697.987606),
        Currency(code: "trx", name: "TRON", symbol: "", rate: 15.62182),
        Currency(code: "tjs", name: "Tajikistani Somoni", symbol: "", rate: 10.919177),
        Currency(code: "tzs", name: "Tanzanian Shilling", symbol: "", rate: 2341.959784),
        Currency(code: "thb", name: "Thai Baht", symbol: "", rate: 34.09038),
        Currency(code: "top", name: "Tongan Paʻanga", symbol: "", rate: 2.351705),
        Currency(code: "ttd", name: "Trinidad & Tobago Dollar", symbol: "", rate: 6.807593),
        Currency(code: "tnd", name: "Tunisian Dinar", symbol: "", rate: 3.129039),
        Currency(code: "try", name: "Turkish Lira", symbol: "", rate: 19.034044),
        Currency(code: "tmt", name: "Turkmenistani Manat", symbol: "", rate: 3.500001),
        Currency(code: "usdc", name: "USD Coin", symbol: "", rate: 1.000124),
        Currency(code: "ugx", name: "Ugandan Shilling", symbol: "", rate: 3775.96034),
        Currency(code: "uah", name: "Ukrainian Hryvnia", symbol: "₴", rate: 36.962693),
        Currency(code: "aed", name: "United Arab Emirates Dirham", symbol: "", rate: 3.672552),
        Currency(code: "usd", name: "United States Dollar", symbol: "$", rate: 1.0),
        Currency(code: "uyu", name: "Uruguayan Peso", symbol: "", rate: 39.025994),
        Currency(code: "uzs", name: "Uzbekistani Som", symbol: "", rate: 11418.295277),
        Currency(code: "vuv", name: "Vanuatu Vatu", symbol: "", rate: 118.89263),
        Currency(code: "vet", name: "Vechain", symbol: "", rate: 44.017098),
        Currency(code: "vnd", name: "Vietnamese Dong", symbol: "", rate: 23525.007499),
        Currency(code: "xrp", name: "XRP", symbol: "", rate: 2.230823),
        Currency(code: "yer", name: "Yemeni Rial", symbol: "", rate: 250.303673),
        Currency(code: "zmk", name: "Zambian Kwacha", symbol: "", rate: 9001.206458),
        Currency(code: "zwl", name: "Zimbabwean Dollar", symbol: "", rate: 321.999695),
    ]

}
